spring.application.name=prod
server.port=9090

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.config.server.git.uri=https://github.com/lavanya220905-crypto/PDA4_Config_prod
spring.cloud.config.server.git.clone-on-start=true
